CREATE DATABASE IF NOT EXISTS SCRIPTSDB;

USE SCRIPTSDB;

CREATE TABLE SCRIPTS(
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
STATUS varchar(20) DEFAULT 'UNREALIZED'
);

SELECT * FROM SCRIPTS;


insert into SCRIPTS (NAME) values ('DOC1');
insert into SCRIPTS (NAME) values ('DOC2');


DROP TABLE SCRIPTS;
